version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    network_mode: default
    command: ["--config=/etc/otel-collector.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
    - ./otel-collector.yaml:/etc/otel-collector.yaml
    restart: unless-stopped