version: '3'

services:
  tempo:
    image: grafana/tempo:2.4.1
    network_mode: default
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/data/tempo
    ports:
      - "3300:3200"
      - "9096:9095"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped
    command: -config.file=/etc/tempo.yaml